import json
import re
from agent.state import DiagnosisState
from agent.llm import call_llm


DIAGNOSIS_PROMPT = """
You are an AIOps incident diagnosis agent.

Your task is to produce a human-readable diagnosis from already analyzed evidence.

Important:
- Root cause candidates were generated by a deterministic statistical pipeline.
- Do NOT invent a different root cause.
- Prefer the highest ranked candidate unless evidence strongly contradicts it.
- Your job is to explain WHY the candidate is likely correct.
- Only use facts present in the evidence.
- Never assume infrastructure changes that are not mentioned.

Remediation guidelines (Action selection):
restart_service
- Application unavailable
- Redis unavailable
- Memory leak requiring temporary recovery

scale_out
- Sustained CPU saturation
- High request rate causing overload

flush_cache
- Stale or corrupted cache only
- Never use for latency

rollback_deploy
- Recent deployment strongly linked to incident

none
- No safe automated remediation exists
- Root cause is external
- More investigation required

Before recommending remediation:
- Check whether the action logically addresses the root cause metric.
- Do not recommend actions that do not affect the identified metric.

Ranked root cause candidates:

{candidates}


Evidence gathered:

{evidence}


Return ONLY valid JSON:

{{
    "root_cause": "metric name of the most likely root cause",
    "hypothesis": "Short explanation citing specific evidence.",
    "confidence": 0.0,
    "recommended_action": "restart_service | scale_out | flush_cache | rollback_deploy | none",
    "needs_more_evidence": true,
    "reasoning": "Why this action was selected."
}}
"""

def _extract_json(text: str) -> dict:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON object found in LLM response: {text[:200]}")
    return json.loads(match.group(0))

def diagnose(state: DiagnosisState) -> DiagnosisState:
    prompt = DIAGNOSIS_PROMPT.format(
        candidates=json.dumps(state["ranked_candidates"], indent=2, default=str),
        evidence=json.dumps(state["evidence_gathered"], indent=2, default=str),
    )
    response = call_llm(prompt)

    try:
        result = _extract_json(response)
    except (ValueError, json.JSONDecodeError) as e:
        # Fail safe rather than crashing the graph — surface it as a low-confidence,
        # no-action diagnosis so the loop-guard/human review path still triggers.
        state["hypothesis"] = f"LLM output could not be parsed: {e}"
        state["confidence"] = 0.0
        state["remediation_action"] = "none"
        state["needs_more_evidence"] = True
        state["diagnosed_root_cause"] = state["ranked_candidates"][0]["metric"] if state["ranked_candidates"] else None
        state["iterations"] += 1
        return state


    candidate_confidence = (
        state["ranked_candidates"][0]["confidence"]
        if state["ranked_candidates"]
        else 0
    )
    llm_confidence = float(result.get("confidence",0))

    state["confidence"] = min(candidate_confidence + 0.15, llm_confidence)

    state["hypothesis"] = result.get("hypothesis", "")

    
    state["remediation_action"] = result.get("recommended_action", "none")
    state["diagnosed_root_cause"] = result.get("root_cause")
    state["needs_more_evidence"] = bool(result.get("needs_more_evidence", False))
    state["reasoning"] = result.get("reasoning", "")
    state["iterations"] += 1
    return state

def confidence_check(state: DiagnosisState) -> str:

    # hard safety limit
    if state["iterations"] >= 3:
        return "finalize"

    # confident diagnosis
    if state["confidence"] >= 0.7:
        return "finalize"

    # uncertain diagnosis
    return "gather_evidence"