import json
from pathlib import Path
from datetime import datetime
from service.logger import LOG_FILE
from detector.rootcause.analysis import DEPENDENCY_PRIOR

DEPLOY_FILE = Path("logs/deploys.jsonl")
INCIDENT_LOG = Path("chaos/incidents.log")

DIAGNOSIS_PROMPT = """
You are an AIOps incident diagnosis agent.

Your task is to produce a human-readable diagnosis from already analyzed evidence.

Important:
- Root cause candidates were generated by a deterministic statistical pipeline.
- Do NOT invent a different root cause.
- Prefer the highest ranked candidate unless evidence strongly contradicts it.
- Your job is to explain WHY the candidate is likely correct.
- Only use facts present in the evidence.
- Never assume infrastructure changes that are not mentioned.

Remediation guidelines (Action selection):
restart_service
- Application unavailable
- Redis unavailable
- Memory leak requiring temporary recovery

scale_out
- Sustained CPU saturation
- High request rate causing overload

flush_cache
- Stale or corrupted cache only
- Never use for latency

rollback_deploy
- Recent deployment strongly linked to incident

none
- No safe automated remediation exists
- Root cause is external
- More investigation required

Before recommending remediation:
- Check whether the action logically addresses the root cause metric.
- Do not recommend actions that do not affect the identified metric.

Note: 
Redis latency alone is NOT evidence that the application should be restarted.

Only recommend restart_service if evidence indicates the application itself is unhealthy,
offline, or failing.

If the evidence only shows elevated Redis latency,
prefer "none" unless cache corruption or cache inconsistency is explicitly shown.

Ranked root cause candidates:

{candidates}


Evidence gathered:

{evidence}


Return ONLY valid JSON:

{{
    "root_cause": "metric name of the most likely root cause",
    "hypothesis": "Short explanation citing specific evidence.",
    "confidence": 0.0,
    "recommended_action": "restart_service | scale_out | flush_cache | rollback_deploy | none",
    "needs_more_evidence": true,
    "reasoning": "Why this action was selected."
}}
"""


def get_related_metrics(metric: str) -> set[str]:
    related = set(DEPENDENCY_PRIOR.get(metric, {}).get("can_cause", []))
    for m, cfg in DEPENDENCY_PRIOR.items():
        if metric in cfg.get("can_cause", []):
            related.add(m)
    return related

def load_incident_history():
    incidents = []

    if not INCIDENT_LOG.exists():
        return incidents

    with open(INCIDENT_LOG) as f:
        for line in f:
            incidents.append(json.loads(line))

    return incidents

def load_deploy_history():

    events = []

    if not DEPLOY_FILE.exists():
        return events

    with open(DEPLOY_FILE) as f:
        for line in f:
            events.append(json.loads(line))

    return events

def query_deploys(start, end):

    nearby = []

    for event in load_deploy_history():

        ts = datetime.fromisoformat(event["timestamp"])

        if start <= ts <= end:
            nearby.append(event)

    return nearby

def load_logs(start, end):

    if isinstance(start, str):
        start = datetime.fromisoformat(start)

    if isinstance(end, str):
        end = datetime.fromisoformat(end)

    events = []

    with open(LOG_FILE) as f:
        for line in f:
            record = json.loads(line)

            ts = datetime.fromisoformat(
                record["timestamp"]
            )

            if start <= ts <= end:
                events.append(record)

    return events