import json
from pathlib import Path
from datetime import datetime
from service.logger import LOG_FILE
from detector.rootcause.analysis import DEPENDENCY_PRIOR

DEPLOY_FILE = Path("logs/deploys.jsonl")
INCIDENT_LOG = Path("chaos/incidents.log")

DIAGNOSIS_PROMPT = """
You are an AIOps incident diagnosis agent.

Your task is to produce a human-readable diagnosis from already analyzed evidence.

Important:
Root cause candidates were generated by a deterministic statistical pipeline.

The highest ranked candidate is usually correct.

However, you are responsible for resolving ambiguous cases.

When the confidence gap between the all candidates within the confidence margin is below 0.15, perform an active comparison between them.

Do not automatically accept the top candidate.

Compare:
- temporal ordering
- metric behavior pattern
- correlation strength
- known failure signatures
- whether the candidate represents a root cause or a downstream symptom

Override the top candidate if another candidate has stronger causal explanation.

If the confidence gap is large (>0.15), accept the top candidate.

Prefer causes over symptoms. 
Also note the following:
Sudden onset increases the likelihood a metric is causal for spike-type incidents; sustained gradual buildup increases the likelihood a metric is causal for leak-type incidents. Judge based on the shape of the change, not just how early it started

IMPORTANT: 
Onset timing for process_resident_memory_bytes is not reliable evidence of causal ordering, since memory usage naturally ramps during process startup — weigh its behavior/correlation instead.

- Your job is to explain WHY the candidate is likely correct.
- Only use facts present in the evidence.
- Never assume infrastructure changes that are not mentioned.

Remediation guidelines (Action selection):
restart_service
- Application unavailable
- Redis unavailable
- Memory leak requiring temporary recovery

scale_out
- Sustained CPU saturation
- High request rate causing overload

flush_cache
- Stale or corrupted cache only
- Never use for latency

rollback_deploy
- Recent deployment strongly linked to incident

none
- No safe automated remediation exists
- Root cause is external
- More investigation required

Before recommending remediation:
- Check whether the action logically addresses the root cause metric.
- Do not recommend actions that do not affect the identified metric.

Note: 
Redis latency alone is NOT evidence that the application should be restarted.

Only recommend restart_service if evidence indicates the application itself is unhealthy,
offline, or failing.

If the evidence only shows elevated Redis latency,
prefer "none" unless cache corruption or cache inconsistency is explicitly shown.

Ranked root cause candidates:

{candidates}

Candidate comparison requirement:

For the top candidate and every other candidate within the confidence margin:
1. Why the top candidate could be correct.
2. Why the others could be correct.
3. Which evidence favors one over the other.

If another candidate better explains the incident, override.
Evidence gathered:

{evidence}

Candidate confidence margin:

{candidate_confidence}


Return ONLY valid JSON:

{{
    "root_cause": "metric name of the most likely root cause",
    "hypothesis": "Short explanation citing specific evidence.",
    "confidence": 0.0,
    "recommended_action": "restart_service | scale_out | flush_cache | rollback_deploy | none",
    "needs_more_evidence": true,
    "reasoning": "Why this action was selected."
}}
"""


def classify_behavior(series, onset_frac):
    """series: the metric's values over the incident window, in order.
    onset_frac: your existing onset value (0=start, 1=end)."""
    n = len(series)
    early = series[:max(1, n // 3)]
    late = series[-max(1, n // 3):]

    early_mean = sum(early) / len(early)
    late_mean = sum(late) / len(late)
    overall_range = max(series) - min(series) or 1e-9

    # how much of the total movement happened in the last third
    late_share = abs(late_mean - early_mean) / overall_range

    if onset_frac <= 0.2 and late_share < 0.3:
        shape = "sudden early spike, then flat/recovering"
    elif onset_frac >= 0.6:
        shape = "gradual buildup, still rising near end of window"
    elif late_share >= 0.5:
        shape = "steadily increasing across the window"
    else:
        shape = "moderate deviation, no strong directional trend"

    return shape

def get_related_metrics(metric: str) -> set[str]:
    related = set(DEPENDENCY_PRIOR.get(metric, {}).get("can_cause", []))
    for m, cfg in DEPENDENCY_PRIOR.items():
        if metric in cfg.get("can_cause", []):
            related.add(m)
    return related

def load_incident_history():
    incidents = []

    if not INCIDENT_LOG.exists():
        return incidents

    with open(INCIDENT_LOG) as f:
        for line in f:
            incidents.append(json.loads(line))

    return incidents

def load_deploy_history():

    events = []

    if not DEPLOY_FILE.exists():
        return events

    with open(DEPLOY_FILE) as f:
        for line in f:
            events.append(json.loads(line))

    return events

def query_deploys(start, end):

    nearby = []

    for event in load_deploy_history():

        ts = datetime.fromisoformat(event["timestamp"])

        if start <= ts <= end:
            nearby.append(event)

    return nearby

def load_logs(start, end):

    if isinstance(start, str):
        start = datetime.fromisoformat(start)

    if isinstance(end, str):
        end = datetime.fromisoformat(end)

    events = []

    with open(LOG_FILE) as f:
        for line in f:
            record = json.loads(line)

            ts = datetime.fromisoformat(
                record["timestamp"]
            )

            if start <= ts <= end:
                events.append(record)

    return events